TAG_MAP: dict[str, int] = {
    # Party (1)
    "battle": 1,
    "dance": 1,
    "dj": 1,
    "fiesta": 1,
    "party": 1,
    # Latin (2)
    "latin": 2,
    "mariachi": 2,
    # Techno / House (4)
    "electro": 4,
    "electronica": 4,
    "elektronica": 4,
    "house": 4,
    "psytech": 4,
    "psytrance": 4,
    "techno": 4,
    # Themed (6)
    "deltalder": 6,
    "football": 6,
    "politics": 6,
    # Indie / Rock (8)
    "alternativerock": 8,
    "art-rock": 8,
    "artrock": 8,
    "bluesrock": 8,
    "britpop": 8,
    "countryrock": 8,
    "desertrock": 8,
    "dreampop": 8,
    "electronicrock": 8,
    "electrorock": 8,
    "folkrock": 8,
    "garagerock": 8,
    "gothicamericana": 8,
    "indie": 8,
    "indiefolk": 8,
    "indiepop": 8,
    "indierock": 8,
    "neo-prog": 8,
    "newwave": 8,
    "poppunk": 8,
    "poprock": 8,
    "postpunk": 8,
    "postrock": 8,
    "powerpop": 8,
    "prog": 8,
    "progressiverock": 8,
    "punkrock": 8,
    "rock": 8,
    "shoegaze": 8,
    "softrock": 8,
    "southernrock": 8,
    "punk": 8,
    "goth": 8,
    # Hip-Hop / R&B (9)
    "hiphop": 9,
    "r&b": 9,
    "rap": 9,
    "popsoul": 9,
    "trap": 9,
    # Live Music (10)
    "brass": 10,
    "choir": 10,
    "covers": 10,
    "festmusikk": 10,
    "psalms": 10,
    "tribute": 10,
    "worldcup": 6,
    "worldmusic": 10,
    # Jazz & Blues (11)
    "blues": 11,
    "jazz": 11,
    "jazzpop": 11,
    # Disco / Funk (12)
    "disco": 12,
    "soul": 12,
    "funk": 12,
    # Folk / Americana (13)
    "americana": 13,
    "bygdecountry": 13,
    "country": 13,
    "countrypop": 13,
    "countrypunk": 13,
    "folk": 13,
    "folkpop": 13,
    "roots": 13,
    "singersingwriter": 13,
    "singersongwriter": 13,
    "visepop": 13,
    "world": 13,
    # Games & Quiz (14)
    "quiz": 14,
    # Pop (15)
    "alternativepop": 15,
    "electropop": 15,
    "hits": 15,
    "hyperpop": 15,
    "pop": 15,
    "synthpop": 15,
    # Comedy & Shows (16)
    "comedy": 16,
    "show": 16,
    "standup": 16,
    # Electronic / Experimental (21)
    "ambient": 21,
    "avantgarde": 21,
    "experimental": 21,
    "industrial": 21,
    "punkrave": 21,
    "darkwave": 21,
    # Culture & Experiences (22)
    "exhibition": 22,
    "livepodcast": 22,
    # Metal (23)
    "alternativemetal": 23,
    "blackmetal": 23,
    "deathcore": 23,
    "deathmetal": 23,
    "doom": 23,
    "hardcore": 23,
    "hardcorepunk": 23,
    "hardrock": 23,
    "heavymetal": 23,
    "melodicmetal": 23,
    "metal": 23,
    "metalcore": 23,
    "metallica": 23,
    "posthardcore": 23,
    "powermetal": 23,
    "progressivemetal": 23,
    "sludge": 23,
    "stoner": 23,
    "stonerrock": 23,
    "symphonicmetal": 23,
    "technicalmetal": 23,
    "thrashmetal": 23,
    # Reggae & Ska (24)
    "dancehall": 24,
    "reggae": 24,
}
